### ISSUE TITLE
Issue with Fungi

### ISSUE THREAD

**Issue by cech12** [DigglesMods/RevisedPlanner#4]
![Screenshot_20220604-154948_Discord.jpg](https://user-images.githubusercontent.com/16005054/172003705-41016872-ca10-4de5-8930-c1c6bc8d4761.jpg)

**Comment by saibantes** [comment]
I improved the harvesting of mushrooms in farms. In particular, unreachable mushrooms will be blacklisted for some time, so that other resources are considered first.
This is part of pull request #7.

**Comment by cech12** [comment]
fixed by #7
